#include <iostream>
#include <ctype.h>
#include <sstream>
#include <vector>
#include <string>
#include <map>
#include <algorithm>
#include <unordered_map>
#include <cmath>
#include <unordered_set>
#include <set>
#include <queue>
#include <deque>
#include <functional>
#include <stack>
#include <cstdint>
#include <stdexcept>
#include <cstdint>
#include <limits>
using namespace std;
